[theme]
primaryColor = "#4a90e2"
backgroundColor = "#0a0e27"
secondaryBackgroundColor = "#1a1f3a"
textColor = "#e0e6ed"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
enableXsrfProtection = false
